services:
  radiobox:
    build: .
    container_name: radiobox
    restart: always
    volumes:
      - "./logs:/app/logs"
      - "./mp3:/app/mp3"
      - "./schema:/app/schema"
      - "./json:/app/json"
    networks:
      - icecast_radiobox_network
networks:
  icecast_radiobox_network:
    external: true
