services:
  radiobox:
    build: .
    restart: always
    extra_hosts:
      - "radio-z.net:49.12.17.76"
      - "snd.radio-z.net:78.47.182.99"
    volumes:
      - "./logs:/app/logs"
      - "./mp3:/app/mp3"
      - "./schema:/app/schema"
      - "./json:/app/json"
